service: sls-data-pipe-glue-orch

plugins:
  - serverless-iam-roles-per-function
  - serverless-lumigo
  - serverless-pseudo-parameters
  - serverless-prune-plugin

custom:
  lumigo:
    token: ${ssm:/lumigo/token}
    nodePackageManager: npm
  prune:
    automatic: true
    number: 3
provider:
  name: aws
  runtime: nodejs12.x
  profile: cloudway-nick
  stage: dev
  region: eu-west-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  startGlueCrawler:
    handler: handler.hello
    timeout: 5
    environment:
      CRAWLER_NAME: anpr-parquet-step1-crawler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - glue:StartCrawler
        Resource:
          - arn:aws:glue:#{AWS::Region}:#{AWS::AccountId}:crawler/*
    events:
      - schedule:
          rate: cron(15 * * * ? *)
          enabled: true

